package uz.shoh.tjbot.entitys.user.enums;

public enum UserState {
    MAIN,
    ADD_TEST_SUBJECT, ADD_TEST_KEYS,
    ADD_BLOC_TEST_FIRST_COMPULSORY_KEYS, ADD_BLOC_TEST_SECOND_COMPULSORY_KEYS, ADD_BLOC_TEST_THIRD_COMPULSORY_KEYS,
    ADD_BLOC_TEST_FIRST_MAJOR_SUBJECT, ADD_BLOC_TEST_SECOND_MAJOR_SUBJECT,
    ADD_BLOC_TEST_FIRST_MAJOR_SUBJECT_KEYS, ADD_BLOC_TEST_SECOND_MAJOR_SUBJECT_KEYS,
    CHECK_TEST_ANSWER,
    CHECK_BLOCK_TEST_FIRST_COMPULSORY_SUBJECT_ANSWER, CHECK_BLOCK_TEST_SECOND_COMPULSORY_SUBJECT_ANSWER,
    CHECK_BLOCK_TEST_THIRD_COMPULSORY_SUBJECT_ANSWER, CHECK_BLOCK_TEST_FIRST_MAJOR_SUBJECT_ANSWER, CHECK_BLOCK_TEST_SECOND_MAJOR_SUBJECT_ANSWER,
    CHANGE_NAME
}
