bot:
  username: https://t.me/testlarjangi_bot
  token: 6430040250:AAGEQZS4zAgETE70C-bRs81f7p_hVNovJWA
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true